#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 22 19:33:20 2019

@author: usrdel
"""


import numpy as np
import pandas as pd


directorio = "./data/artwork_data.csv"

df_artwork = pd.read_csv(directorio,
                         nrows=5,
                         index_col="id",
                         usecols=["id","artist"])
# Archivos Texto PDF HTML XML CSV JSON
# Binarios
# BDD Relacionales

columnas = ["id", "artist", "title",
            "medium", "year", "acquisitionYear",
            "height", "width", "units"]
df_completo = pd.read_csv(
        directorio,
        index_col="id",
        usecols=columnas)

directorio_guardado = "./data/artwork_data.pickle"

df_completo.to_pickle(directorio_guardado)

df_completo_de_pickle = pd.read_pickle(
        directorio_guardado)









































